import Head from 'next/head'
import Image from 'next/image'
import Sidebar from '../components/sidebar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Whatsapp 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />

      
    </div>
  )
}
